const books = [
    { id: 1, name: "Alice's Adventures in Wonderland", author: "Lewis Carroll", genre: "Fantasy", info: "This whimsical tale of a young girl’s journey into a strange, surreal world is perfect for autumn, when magic seems to linger in the air. Dive into Alice's adventures and let your imagination wander alongside the falling leaves." },
    { id: 2, name: "Norwegian Wood", author: "Haruki Murakami", genre: "Fiction", info: "Set in a world of melancholic beauty, this novel is a bittersweet exploration of love and memory. Its introspective tone and nostalgic atmosphere make it an ideal companion for quiet autumn evenings." },
    { id: 3, name: "Kafka on the Shore", author: "Haruki Murakami", genre: "Magical Realism", info: "With its mysterious characters and surreal twists, 'Kafka on the Shore' mirrors the enigmatic feeling of autumn nights. It’s a deep, engaging read that captures the spirit of self-discovery and magic." },
    { id: 4, name: "After Dark", author: "Haruki Murakami", genre: "Mystery", info: "The story unfolds over a single autumn night, capturing the haunting stillness of the season. This novel’s blend of suspense and mystery invites readers to explore Tokyo’s hidden layers in the early hours." },
    { id: 5, name: "One Dark Window", author: "Rachel Gillig", genre: "Fantasy", info: "A hauntingly atmospheric story filled with dark magic, this fantasy novel perfectly matches the chilly allure of autumn. Its eerie landscapes and mysterious characters will keep you enchanted." },
    { id: 6, name: "The Hobbit", author: "J.R.R. Tolkien", genre: "Fantasy", info: "Bilbo’s journey through enchanting lands filled with danger and wonder is a timeless tale for fall. Its cozy, fireside storytelling style and adventurous spirit make it ideal as the weather cools down." },
    { id: 7, name: "Animal Farm", author: "George Orwell", genre: "Political Satire", info: "This political allegory, set on a seemingly peaceful farm, grows darker as it delves into themes of power and corruption. Perfect for reflective autumn afternoons, it’s a timeless reminder of change and revolution." },
    { id: 8, name: "1984", author: "George Orwell", genre: "Dystopian", info: "Orwell’s chilling vision of a dystopian future is all the more poignant in the introspective autumn season. The novel’s bleak yet compelling world pairs well with the somber beauty of fall." },
    { id: 9, name: "For Whom the Bell Tolls", author: "Ernest Hemingway", genre: "War Fiction", info: "Hemingway’s intense story of war, love, and sacrifice resonates with the quiet intensity of autumn. The novel’s raw emotional depth aligns with the season’s reflective mood." },
    { id: 10, name: "A Moveable Feast", author: "Ernest Hemingway", genre: "Memoir", info: "Set in 1920s Paris, this memoir captures Hemingway’s youthful days as a writer. Its charming prose and nostalgic insights make it a cozy autumn read, perfect for warm drinks and sweater weather." },
    { id: 11, name: "The Tales of Beedle the Bard", author: "J.K. Rowling", genre: "Fantasy", info: "This collection of magical fairy tales, beloved by wizards and Muggles alike, offers a sense of wonder perfect for autumn. Each tale carries moral lessons wrapped in enchantment, making it an ideal read as the days grow shorter." },
    { id: 12, name: "Rebecca", author: "Daphne du Maurier", genre: "Fiction", info: "This haunting tale of suspense and mystery is perfect for autumn. The story’s eerie atmosphere and intricate plot captivate readers as they explore themes of love, jealousy, and identity." },
    { id: 13, name: "The Picture of Dorian Gray", author: "Oscar Wilde", genre: "Fiction", info: "Wilde’s exploration of beauty, morality, and vanity feels especially poignant in the contemplative autumn season. The novel’s dark themes resonate as the leaves begin to fall." },
    { id: 14, name: "The Night Circus", author: "Erin Morgenstern", genre: "Fantasy", info: "Set in a magical circus that appears only at night, this enchanting tale evokes the mystique of autumn nights and draws readers into a world of wonder and intrigue." },
    { id: 15, name: "Dracula", author: "Bram Stoker", genre: "Horror", info: "Stoker’s classic horror novel brings the chill of autumn to life with its suspenseful storytelling. Perfect for reading on dark, windy nights, it embodies the haunting spirit of the season." },
    { id: 16, name: "The Secret History", author: "Donna Tartt", genre: "Thriller", info: "This novel’s introspective and suspenseful narrative is a perfect match for autumn. Tartt’s characters and plot twists make it an ideal choice for a season marked by reflection and intrigue." }
  ];

  module.exports = books;